<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Hammids-MacBook-Pro.local" name="sample.ServicesSampleTestIT" tests="3" failures="1" timestamp="11 Jul 2018 17:04:06 GMT" time="0.264" errors="0">
  <testcase name="sampleServicesAddressTest" time="0.181" classname="sample.ServicesSampleTestIT">
    <failure type="java.lang.AssertionError" message="Detailed results found at: sample_ServicesSampleTestIT_sampleServicesAddressTestNONE.html expected:&lt;0 errors&gt; but was:&lt;1 errors&gt;">
      <![CDATA[java.lang.AssertionError: Detailed results found at: sample_ServicesSampleTestIT_sampleServicesAddressTestNONE.html expected:<0 errors> but was:<1 errors>
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:101)
	at com.coveros.selenified.Selenified.finish(Selenified.java:358)
	at sample.ServicesSampleTestIT.sampleServicesAddressTest(ServicesSampleTestIT.java:53)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </failure>
  </testcase> <!-- sampleServicesAddressTest -->
  <testcase name="sampleServicesCityTest" time="0.051" classname="sample.ServicesSampleTestIT"/>
  <testcase name="sampleServicesZipCountryTest" time="0.032" classname="sample.ServicesSampleTestIT"/>
</testsuite> <!-- sample.ServicesSampleTestIT -->
